import numpy as np


# Init the minutiae set list
minutiae = []

# minutiae 1
minutiae.append(np.array([[1, 0, 0], 
                          [0, 1, 0], 
                          [0, 0, 0]]))
# minutiae 2
minutiae.append(np.array([[0, 1, 0], 
                          [0, 1, 0], 
                          [0, 0, 0]]))
# minutiae 3
minutiae.append(np.array([[0, 0, 1], 
                          [0, 1, 0], 
                          [0, 0, 0]]))
# minutiae 4
minutiae.append(np.array([[0, 0, 0], 
                          [1, 1, 0], 
                          [0, 0, 0]]))
# minutiae 5
minutiae.append(np.array([[0, 0, 0], 
                          [0, 1, 1], 
                          [0, 0, 0]]))
# minutiae 6
minutiae.append(np.array([[0, 0, 0], 
                          [0, 1, 0], 
                          [1, 0, 0]]))
# minutiae 7
minutiae.append(np.array([[0, 0, 0], 
                          [0, 1, 0], 
                          [0, 1, 0]]))
# minutiae 8
minutiae.append(np.array([[0, 0, 0], 
                          [0, 1, 0], 
                          [0, 0, 1]]))

# Define Bifurcations with 3 endpoints
# minutiae 9
minutiae.append(np.array([[1, 0, 1], 
                          [0, 1, 0], 
                          [0, 1, 0]]))
# minutiae 10
minutiae.append(np.array([[1, 0, 1], 
                          [0, 1, 0], 
                          [0, 0, 1]]))
# minutiae 11
minutiae.append(np.array([[1, 0, 1], 
                          [0, 1, 0], 
                          [1, 0, 0]]))
# minutiae 12
minutiae.append(np.array([[1, 0, 0], 
                          [0, 1, 1], 
                          [0, 1, 0]]))
# minutiae 13
minutiae.append(np.array([[1, 0, 0], 
                          [0, 1, 0], 
                          [1, 0, 1]]))
# minutiae 14
minutiae.append(np.array([[1, 0, 0], 
                          [0, 1, 1], 
                          [1, 0, 0]]))
# minutiae 15
minutiae.append(np.array([[0, 0, 1], 
                          [0, 1, 0], 
                          [1, 0, 1]]))
# minutiae 16
minutiae.append(np.array([[0, 0, 1], 
                          [1, 1, 0], 
                          [0, 0, 1]]))
# minutiae 17
minutiae.append(np.array([[0, 0, 1], 
                          [1, 1, 0], 
                          [0, 1, 0]]))
# minutiae 18
minutiae.append(np.array([[0, 1, 0], 
                          [0, 1, 1], 
                          [0, 1, 0]]))
# minutiae 19
minutiae.append(np.array([[0, 1, 0], 
                          [0, 1, 1], 
                          [1, 0, 0]]))
# minutiae 20
minutiae.append(np.array([[0, 1, 0], 
                          [1, 1, 1], 
                          [0, 0, 0]]))
# minutiae 21
minutiae.append(np.array([[0, 1, 0], 
                          [0, 1, 0], 
                          [1, 0, 1]]))
# minutiae 22
minutiae.append(np.array([[0, 1, 0], 
                          [1, 1, 0], 
                          [0, 1, 0]]))
# minutiae 23
minutiae.append(np.array([[0, 1, 0], 
                          [1, 1, 0], 
                          [0, 0, 1]]))
# minutiae 24
minutiae.append(np.array([[0, 0, 0], 
                          [0, 1, 0], 
                          [1, 1, 1]]))
# minutiae 25
minutiae.append(np.array([[0, 0, 0], 
                          [1, 1, 1], 
                          [0, 1, 0]]))
# minutiae 26
minutiae.append(np.array([[0, 0, 1], 
                          [1, 1, 1], 
                          [0, 0, 0]]))
# minutiae 27
minutiae.append(np.array([[1, 0, 0],
                          [0, 1, 0],
                          [1, 1, 0]]))
# minutiae 28
minutiae.append(np.array([[1, 0, 0],
                          [1, 1, 1],
                          [0, 0, 0]]))
# minutiae 29
minutiae.append(np.array([[0, 1, 0],
                          [0, 1, 0],
                          [1, 1, 0]]))
# minutiae 30
minutiae.append(np.array([[0, 0, 0],
                          [1, 1, 1],
                          [1, 0, 0]]))
# minutiae 31
minutiae.append(np.array([[1, 0, 0],
                          [0, 1, 1],
                          [0, 0, 1]]))
# minutiae 32
minutiae.append(np.array([[1, 0, 0],
                          [1, 1, 0],
                          [0, 0, 1]]))
# minutiae 33
minutiae.append(np.array([[1, 1, 0],
                          [0, 1, 0],
                          [0, 1, 0]]))
# minutiae 34
minutiae.append(np.array([[1, 1, 0],
                          [0, 1, 0],
                          [0, 0, 1]]))
# minutiae 35
minutiae.append(np.array([[0, 1, 1],
                          [0, 1, 0],
                          [0, 1, 0]]))
# minutiae 36
minutiae.append(np.array([[0, 0, 1],
                          [0, 1, 1],
                          [0, 1, 0]]))
# minutiae 37
minutiae.append(np.array([[0, 1, 0],
                          [0, 1, 0],
                          [0, 1, 1]]))
# minutiae 38
minutiae.append(np.array([[0, 0, 1],
                          [0, 1, 1],
                          [1, 0, 0]]))
# minutiae 39
minutiae.append(np.array([[0, 0, 1],
                          [1, 1, 0],
                          [1, 0, 0]]))
# minutiae 40
minutiae.append(np.array([[0, 0, 1],
                          [0, 1, 0],
                          [1, 1, 0]]))
# minutiae 41
minutiae.append(np.array([[1, 1, 0],
                          [0, 1, 0],
                          [1, 0, 0]]))
# minutiae 42
minutiae.append(np.array([[1, 0, 0],
                          [0, 1, 0],
                          [0, 1, 1]]))
# minutiae 43
minutiae.append(np.array([[0, 0, 0],
                          [1, 1, 1],
                          [0, 0, 1]]))
# minutiae 44
minutiae.append(np.array([[0, 0, 0],
                          [0, 1, 1],
                          [1, 0, 1]]))
# minutiae 45
minutiae.append(np.array([[1, 0, 1],
                          [1, 1, 0],
                          [0, 0, 0]]))
# minutiae 46
minutiae.append(np.array([[0, 1, 1],
                          [0, 1, 0],
                          [1, 0, 0]]))
# minutiae 47
minutiae.append(np.array([[0, 1, 1],
                          [0, 1, 0],
                          [0, 0, 1]]))
# minutiae 48
minutiae.append(np.array([[0, 0, 0],
                          [1, 1, 0],
                          [1, 0, 1]]))
# minutiae 49
minutiae.append(np.array([[0, 0, 1],
                          [0, 1, 0],
                          [0, 1, 1]]))
# minutiae 50
minutiae.append(np.array([[1, 0, 1],
                          [0, 1, 1],
                          [0, 0, 0]]))
